package com.tcs.user_auth_management.emuns;

import lombok.Getter;

@Getter
public enum AuditLogEvent {
  LOGIN_SUCCESS("LOGIN_SUCCESS"),
  LOGIN_FAILURE("LOGIN_FAILURE"),
  LOGOUT("LOGOUT"),
  LOGOUT_ALL_SESSION("LOGOUT_ALL_SESSION"),
  PASSWORD_CHANGE("PASSWORD_CHANGE"),
  ACCOUNT_LOCKED("ACCOUNT_LOCKED"),
  ACCOUNT_UNLOCKED("ACCOUNT_UNLOCKED"),
  PROFILE_UPDATE("PROFILE_UPDATE"),
  PASSWORD_RESET_BY_EMAIL("PASSWORD_RESET_BY_EMAIL"),
  PASSWORD_RESET_BY_OLD_PASSWORD("PASSWORD_RESET_BY_OLD_PASSWORD"),
  VERIFY_EMAIL("VERIFY_EMAIL"),
  SEND_VERIFY_EMAIL("SEND_VERIFY_EMAIL"),
  SEND_FORGOT_PASSWORD_EMAIL("SEND_FORGOT_PASSWORD_EMAIL"),
  USER_REGISTRATION("USER_REGISTRATION");

  private final String action;

  AuditLogEvent(String action) {
    this.action = action;
  }

  @Override
  public String toString() {
    return this.action;
  }
}
